name: 'Snowplow Data Structures CI - Check'
description: 'Verify that all of your app''s data structures dependencies are already deployed into the specified environment'
author: 'Snowplow Analytics'
branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  organization-id:
    description: 'UUID of the Snowplow organization as found in Snowplow BDP Console'
    required: true
  api-key: 
    description: 'Snowplow BDP Console API key'
    required: true
  manifest-path:  
    description: 'Absolute path to the manifest file describing data structures dependencies of your app'
    required: true
    default: 'snowplow-schemas.json'
  environment: 
    description: 'The environment against which the check is performed'
    required: true

runs:
  using: 'docker'
  image: '../Dockerfile'
  env:
    ORGANIZATION_ID: ${{ inputs.organization-id }}
    API_KEY: ${{ inputs.api-key }}
  args:
    - 'check'
    - '--manifestPath'
    - ${{ inputs.manifest-path }}
    - '--environment'
    - ${{ inputs.environment }}