name: 'Snowplow Schema CI - Check'
description: 'Verify that all of your app''s schema dependencies are already deployed into the specified environment'
author: 'Snowplow Analytics'
branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  manifest-path:  
    description: 'Absolute path to the manifest file describing schema dependencies of your app'
    required: true
    default: 'snowplow-schemas.json'
  username:
    description: 'Username of the CI user'
    required: true
  password: 
    description: 'Password of the CI user'
    required: true 
  environment: 
    description: 'The environment against which the check is performed'
    required: true

runs:
  using: 'docker'
  image: '../Dockerfile'
  args:
    - 'check'
    - '--manifestPath'
    - ${{ inputs.manifest-path }}
    - '--username'
    - ${{ inputs.username }}
    - '--password'
    - ${{ inputs.password }}
    - '--environment'
    - ${{ inputs.environment }}